import Head from "next/head";
import { useState } from "react";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavbarCustom from "@/pages/_navbar";
import {
	Button, Row, Col, Container
} from "reactstrap";
import {
	useAccount,
	useConnect,
	useDisconnect,
	useEnsAvatar,
	useEnsName,
} from 'wagmi';

export default function Home() {
	const { address, connector, isConnected } = useAccount();
	const connect = useConnect();
	const disconnect = useDisconnect();

	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};


	const [msg,setMsg] = useState('');
	const [msgColor,setMsgColor] = useState('black');

	const checkAddress = async () => {
		console.log('Checking Address',isConnected);
		if (!isConnected){
			setMsg('Please Connect Your Wallet');
			setMsgColor('red');
			return;
		}
		try {
			const response = await fetch('/api/checkWalletAddress', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify(address),
			});
			const res = await response.json();
			console.log(res)
			if (res.status){
				setMsg('You Are Eligible For The AirDrop');
				setMsgColor('green');
			}
			else{
				setMsg('You Are Not Eligible For The AirDrop');
				setMsgColor('red');
			}
		} catch (error) {
			setMsg('You Are Not Eligible For The AirDrop');
			setMsgColor('red');
			console.error('Error updating exchanges:', error);
 		}
	}

	return (
		<div style={{color: '#B4B4B4'}}>
			<Head>
				<title>Solar Dex AirDrop</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavbarCustom />
			<Container className={'text-center'}>
				<Row>
					<Col className={'mt-5 box-tier'} >
						<h1>Tier 1</h1>
						<Button  className={'mt-5 btn-bg'} disabled={true}> Claim </Button>
					</Col>
					<Col className={'mt-5 box-tier'}>
						<h1>Tier 2</h1>
						<Button className={'mt-5 btn-bg'} disabled={true}> Claim </Button>
					</Col>
				</Row>
					<Button onClick={checkAddress} className={'mt-5 ml-auto mr-auto p-3 btn-bg '}> Check Address </Button>
				<p className={'mt-5'} style={{color: msgColor, fontWeight:600, fontSize: '20px' }}>{msg}</p>

 			</Container>
 		</div>
	);
}
