import Head from "next/head";
import { useState } from "react";
import 'bootstrap/dist/css/bootstrap.min.css';
import NavbarCustom from "@/pages/_navbar";
import {
	Button, Row, Col, Container, Modal,ModalHeader, ModalBody, ModalFooter
} from "reactstrap";
export default function Home() {
	const [isNetworkSwitchHighlighted, setIsNetworkSwitchHighlighted] =
		useState(false);
	const [isConnectHighlighted, setIsConnectHighlighted] = useState(false);

	const closeAll = () => {
		setIsNetworkSwitchHighlighted(false);
		setIsConnectHighlighted(false);
	};
	const [modal, setModal] = useState(false);

	const toggle = () => setModal(!modal);

	return (
		<div style={{color: '#B4B4B4'}}>
			<Head>
				<title>Solar Dex AirDrop</title>
				<meta
					name="description"
					content="Generated by create-wc-dapp"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<NavbarCustom/>
			<Container>
				<Row>
					<Col className={'mt-5 box-tier'} >
						<h1>Tier 1</h1>
						<Button  className={'mt-5 btn-bg'}> Claim </Button>
					</Col>
					<Col className={'mt-5 box-tier'}>
						<h1>Tier 2</h1>
						<Button onClick={toggle} className={'mt-5 btn-bg'}> Claim </Button>
					</Col>
				</Row>
			</Container>
			<Modal isOpen={modal} toggle={toggle} >
				<ModalHeader toggle={toggle}>Result</ModalHeader>
				<ModalBody>
					Coming Soon.....
				</ModalBody>
				<ModalFooter>
					<Button color="secondary" onClick={toggle}>
						Cancel
					</Button>
				</ModalFooter>
			</Modal>
 		</div>
	);
}
